import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font--poppins",
});

export const metadata: Metadata = {
  title: "Pusat Arsip Kepolisian",
  description: "Generated by Fizora",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable}  text-2xl  antialiased `}>
        {children}
      </body>
    </html>
  );
}
